# Generated by Django 3.2.6 on 2021-09-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_deviceid_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='share',
            field=models.ManyToManyField(blank=True, related_name='news_share', to='news.Share'),
        ),
    ]
