# Generated by Django 3.2.6 on 2021-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(default='Testing', max_length=100),
            preserve_default=False,
        ),
    ]
