# Generated by Django 3.2.6 on 2021-09-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
        migrations.RemoveField(
            model_name='news',
            name='share',
        ),
        migrations.AddField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
            preserve_default=False,
        ),
    ]
