# Generated by Django 3.2.6 on 2021-09-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210917_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('news_id', 'device_id')},
        ),
    ]
