# Generated by Django 3.2.6 on 2021-09-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.IntegerField(),
        ),
    ]
