# Generated by Django 3.2.6 on 2021-09-02 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_broadcast_email_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast_email',
            options={'verbose_name': 'BroadCast'},
        ),
        migrations.AddField(
            model_name='broadcast_email',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=225, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
